#!/usr/bin/env bash
# Script that will display information about subdomains

DNS_info () {
    ANSWER=$(dig $2 | grep -A1 'ANSWER SECTION:' | awk 'NR==2 {print $0}')
    echo "The subdomain $1 is a $(echo $ANSWER | awk '{print $4}') record and points to $(echo $ANSWER | awk '{print $5}')"
}

if [[ $# == 1 ]]; then
    subdomains=('www' '100.25.118.239' '54.157.188.156' '54.144.222.197')
    for i in "${subdomains[@]}"; do
	CONCAT="$i.$1"
	DNS_info $i $CONCAT
    done
else
    CONCAT="$2.$1"
    DNS_info $2 $CONCAT
fi
