#!/usr/bin/env bash
# A script written in Bash that moves files from a client to a server.
# We are passing the following parameters to the scp command:
# PATH_TO_FILE to be copied to the server, IP of the server, USER on the server,
# PATH_TO_IDENTITY_FILE for user authentication, and LOCATION to copy to on the server.

if [ $# -lt 4 ]
then
    echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":"$5"
fi
