#!/usr/bin/env bash
# A bash script that installs Nginx on an Ubuntu machine.
# This script also configures the default webpage to serve "Hello World!"
# and sets up a redirect from /redirect_me to a YouTube channel.

# Update package lists
sudo apt-get update -y

# Install Nginx
sudo apt-get install nginx -y

# Create a default index.html page with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Define the new rule for the redirect
NEW_RULE="\\\n\tlocation = /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=dQw4w9WgXcQ;\n\t}\n"

# Backup the original Nginx default site configuration
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bakup

# Insert the new rule into the Nginx default site configuration
sudo sed -i "53i $NEW_RULE" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart
