#!/usr/bin/env bash
# Configures a new Ubuntu machine to meet the requirements

# Update package list and install nginx
apt-get -y update
apt-get -y install nginx

# Configure Nginx to add a custom response header with the hostname
HOST_NAME=$(hostname)
HEADER="add_header X-Served-By $HOST_NAME;"
CONFIG_FILE="/etc/nginx/sites-available/default"

if ! grep -q "X-Served-By" $CONFIG_FILE; then
    sed -i "23i \\t$HEADER" $CONFIG_FILE
fi

# Create a default index.html page
echo "Hello World!" > /var/www/html/index.html

# Add a redirection to the Nginx configuration
REDIRECT_STRING="location /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=3MbaGJN2ioQ;\n\t}"
if ! grep -q "redirect_me" $CONFIG_FILE; then
    sed -i "42i \\t$REDIRECT_STRING" $CONFIG_FILE
fi

# Add a custom 404 error page to the Nginx configuration
ERROR_PAGE="error_page 404 /custom_404.html;"
CUSTOM_404_CONTENT="Ceci n'est pas une page"
if ! grep -q "error_page 404" $CONFIG_FILE; then
    echo $CUSTOM_404_CONTENT > /var/www/html/custom_404.html
    sed -i "40i \\t$ERROR_PAGE" $CONFIG_FILE
fi

# Restart Nginx to apply the changes
service nginx restart
