#!/usr/bin/env bash
# Script: 5-is_the_host_on_the_network.sh
# Description: Pings an IP address received as an argument 5 times.
# Usage: ./5-is_the_host_on_the_network.sh {IP_ADDRESS}
if [ $# -eq 0 ]
then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
  ping -c 5 "$1"
fi
