#!/usr/bin/env bash
# This script displays a list of currently running processes

# Display header
echo "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"

# Display list of processes
ps aux
