#!/usr/bin/env bash
# This script displays a list of currently running processes

# Display header
echo "PID     PPID    USER       COMMAND"

# Display list of processes with hierarchy
ps aux --forest
