#!/usr/bin/env bash
# Performs the following tasks:
#   1. Creates a file /var/run/myscript.pid containing the script's PID.
#   2. Displays "To infinity and beyond" indefinitely.
#   3. Displays "I hate the kill command" upon receiving a SIGTERM.
#   4. Displays "Y U no love me?!" upon receiving a SIGINT.
#   5. Deletes the file /var/run/myscript.pid and terminates upon
#      receiving a SIGQUIT or SIGTERM.

# Function to remove the PID file and exit
terminator() {
  rm /var/run/myscript.pid
  exit
}

# Write the script's PID to /var/run/myscript.pid
echo "$$" > /var/run/myscript.pid

# Infinite loop to display message and handle signals
while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'terminator' SIGQUIT
done

