#!/usr/bin/env bash
# Script to manage the process manage_my_process.
#   If provided the argument `start`:
#     1. Initiates the manage_my_process.
#     2. Generates a file storing its PID in /var/run/my_process.pid.
#     3. Displays "manage_my_process initiated".
#   If provided the argument `stop`:
#     1. Halts the manage_my_process.
#     2. Removes the file /var/run/my_process.pid.
#     3. Displays "manage_my_process terminated".
#   If provided the argument `restart`:
#     1. Terminates the manage_my_process.
#     2. Deletes the file /var/run/my_process.pid.
#     3. Starts manage_my_process.
#     4. Creates a file storing its PID in /var/run/my_process.pid.
#     5. Shows "manage_my_process restarted".
#   If any other argument or no arguments are provided, shows
#+  "Usage: manage_my_process {start|stop|restart}"

if [ "${1}" == "start" ]; 
then
    ./manage_my_process &
    touch /var/run/my_process.pid
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process initiated"
elif [ "${1}" == "stop" ];
then
    echo "manage_my_process terminated"
    kill "$(cat /var/run/my_process.pid)"
    rm /var/run/my_process.pid
elif [ "${1}" == "restart" ]; 
then
    kill "$(cat /var/run/my_process.pid)"
    rm /var/run/my_process.pid
    ./manage_my_process &
    touch /var/run/my_process.pid
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
