#!/usr/bin/env bash
# shellcheck disable=SC2009
# This script displays lines containing the word "bash" to get the PID of the Bash process

# Use ps command to display processes and grep for the word "bash"
ps aux | grep bash
