#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely with
# a sleep 2 in between each iteration.
# Displays "I am invincible!!!" in between each iteration.

# Set up trap to handle SIGTERM signal
trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop
while true
do
  echo "To infinity and beyond"
  sleep 2
done
