#!/usr/bin/env bash
# Continuously writes the message "I am alive!" to the file /tmp/my_process.
#   Adds a two-second pause between each message.

while true
do
  echo "I am alive!" >> /tmp/my_process
  sleep 2
done
