#!/usr/bin/env bash
# Above line specifies the interpreter to be used, here bash

# Tells a story based on the contents of the `/etc/passwd` file.

# Loop through each line of the /etc/passwd file
while IFS=':' read -r username password uid gid info home shell; do
  # Print a story based on the user information
  echo "The user $username is part of the $gid gang," \
       "lives in $home and rides $shell." \
       "$uid's place is protected by the passcode $password," \
       "more info about the user here: $info"
done < "/etc/passwd"  # Redirects the file /etc/passwd as input for the while loop
