#!/usr/bin/env bash
# This script displays different messages for specific numbers using a case statement

# Initialize counter
counter=1

# Execute loop while counter is less than or equal to 20
while [ $counter -le 20 ]; do
    # Display the current number
    echo $counter
    
    # Check the value of the counter for different messages
    case $counter in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
    esac
    
    # Increment counter
    ((counter++))
done
