#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes

# Initialize variables
hour=0
minute=1

# Execute loop to display hours and minutes
while [ $hour -le 12 ]; do
    # Display hour
    echo "Hour: $hour"
    
    # Display minutes from 1 to 59
    while [ $minute -le 59 ]; do
        echo $minute
        ((minute++))
    done
    
    # Reset minute for the next hour
    minute=1
    
    # Increment hour
    ((hour++))
done
